name: Build and Deploy to the Server

on:
  [push]

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  cd:
    needs: ci

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Gradle custom build
        run: ./gradlew deploy
        working-directory: ./web1

      - name: Rsync to the server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: ./web1/helios-root/
          remote_path: /home/studs/${{ secrets.USERNAME }}/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          remote_port: ${{ secrets.PORT }}

      # Run deploy script
      - name: Run remote deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Running deploy.sh on the server..."
            cd /home/studs/${{ secrets.USERNAME }}/
            sh deploy.sh

      # Add a sleep to wait for services to start
      - name: Wait for services to start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Waiting for services to start..."
            sleep 10

      # Check the status of the Java and httpd services
      - name: Check httpd and Java server status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Checking httpd status..."
            ps aux | grep httpd
            
            echo "Checking Java server status..."
            ps aux | grep java

      # Check logs if any issue occurs
      - name: Check output.log and error.log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Checking output.log..."
            cat "$HOME/output.log"
            
            echo "Checking error.log..."
            cat "$HOME/error.log"

      # Verify the server is up and running by making a request
      - name: Test the deployed server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "Testing server response..."
            curl http://localhost:45455/fcgi-bin/server.jar
